name: issue label automation
on:
  issues:
    types:
      - labeled
jobs:
  issue_labels:
    runs-on: ubuntu-latest
    name: Move labeled card
    steps:
      - uses: nipe0324/update-project-v2-item-field@v2.0.1
        if: "github.event.label.name == 'Status: Cancelled'"
        with:
          project-url: https://github.com/users/ikafurai19706/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          field-name: Status
          field-value: Cancelled
